# Generated by Django 4.0 on 2022-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_nr', models.IntegerField(unique=True)),
                ('chapter_file', models.FileField(upload_to='chapter/')),
            ],
        ),
    ]
