# Generated by Django 4.0 on 2022-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover',
            field=models.ImageField(default=None, upload_to='covers/'),
        ),
    ]
