# Generated by Django 4.0 on 2022-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueFile',
            field=models.FileField(upload_to='static/issue/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='static/sponsors/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='static/team/'),
        ),
        migrations.AlterField(
            model_name='update',
            name='photo',
            field=models.ImageField(upload_to='static/updates/'),
        ),
    ]
