# Generated by Django 4.0 on 2022-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0002_alter_issue_issuefile_alter_sponsor_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueFile',
            field=models.FileField(upload_to='issue/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='update',
            name='photo',
            field=models.ImageField(upload_to='updates/'),
        ),
    ]
