# Generated by Django 4.0 on 2022-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='editor',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
