# Generated by Django 4.0 on 2022-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0002_alter_sponsor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
