# Generated by Django 4.0 on 2022-03-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0003_alter_sponsor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
