# Generated by Django 4.0 on 2022-03-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0003_alter_issue_issuefile_alter_sponsor_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueFile',
            field=models.CharField(max_length=200),
        ),
    ]
