# Generated by Django 3.2.13 on 2022-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0003_chapter_chapter_title_chapter_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_nr',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
