# Generated by Django 3.2.13 on 2022-04-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0004_auto_20220420_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_file',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='editor',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('editor', models.CharField(default=None, max_length=255)),
                ('file', models.FileField(upload_to='chapter/')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ExpressisVerbisApp.chapter')),
            ],
        ),
    ]
