# Generated by Django 4.0 on 2022-03-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0002_issue_cover'),
        ('ExpressisVerbisApp', '0004_alter_issue_issuefile'),
    ]

    operations = [
    ]
