# Generated by Django 4.0 on 2022-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0005_merge_0002_issue_cover_0004_alter_issue_issuefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(default=None, upload_to='expressisverbis/ExpressisVerbisApp/static/covers/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueFile',
            field=models.FileField(upload_to='issue/'),
        ),
    ]
