# Generated by Django 4.0 on 2022-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressisVerbisApp', '0006_alter_issue_cover_alter_issue_issuefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(default=None, upload_to='covers/'),
        ),
    ]
